### ISSUE TITLE
AE2 Spatial Storage does not work due to Biomes O'Plenty?

### ISSUE THREAD

**Issue by quietust** [MechOrigin/NTC2#20]
Modpack version: 1.3.9

All attempts to use the Spatial I/O Port result in failure, logging the following to both `latest.log` and `debug.log`:
```
java.lang.IllegalStateException: The storage cell world is missing.
	at appeng.spatial.SpatialStoragePlotManager.getWorld(SpatialStoragePlotManager.java:51) ~[?:8.4.4]
	at appeng.spatial.SpatialStoragePlotManager.getWorldData(SpatialStoragePlotManager.java:57) ~[?:8.4.4]
	at appeng.spatial.SpatialStoragePlotManager.allocatePlot(SpatialStoragePlotManager.java:70) ~[?:8.4.4]
	at appeng.items.storage.SpatialStorageCellItem.doSpatialTransition(SpatialStorageCellItem.java:141) ~[?:8.4.4]
	at appeng.tile.spatial.SpatialIOPortTileEntity.call(SpatialIOPortTileEntity.java:145) ~[?:8.4.4]
	at appeng.tile.spatial.SpatialIOPortTileEntity.call(SpatialIOPortTileEntity.java:54) ~[?:8.4.4]
	at appeng.hooks.ticking.TickHandler.processQueue(TickHandler.java:439) [?:8.4.4]
	at appeng.hooks.ticking.TickHandler.onServerTick(TickHandler.java:318) [?:8.4.4]
	at appeng.hooks.ticking.TickHandler$$Lambda$13774/962757519.accept(Unknown Source) [?:8.4.4]
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247) [eventbus-4.0.0.jar:?]
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239) [eventbus-4.0.0.jar:?]
	at net.minecraftforge.eventbus.EventBus$$Lambda$2860/1929087517.invoke(Unknown Source) [eventbus-4.0.0.jar:?]
	at net.minecraftforge.eventbus.EventBus$$Lambda$3181/1998093424.invoke(Unknown Source) [eventbus-4.0.0.jar:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) [eventbus-4.0.0.jar:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) [eventbus-4.0.0.jar:?]
	at net.minecraftforge.fml.hooks.BasicEventHooks.onPostServerTick(BasicEventHooks.java:120) [?:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:828) [?:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:78) [?:?]
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:642) [?:?]
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232) [?:?]
	at net.minecraft.server.MinecraftServer$$Lambda$27953/1898761657.run(Unknown Source) [?:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51]
```

Reportedly, this is due to a conflict with Biomes O'Plenty (see AppliedEnergistics/Applied-Energistics-2#4842 and Glitchfiend/BiomesOPlenty#1750).

Until this bug can be resolved, the related quest should probably be removed since there's literally no point in completing it right now.

**Comment by quietust** [comment]
I edited my world's `level.dat` file with NBTExplorer and was able to fix the problem by doing the following:

1. Browse to level.dat -> Data -> WorldGenSettings -> dimensions
2. Create a Compound tag named `appliedenergistics2:spatial_storage` (at the same level as the other dimensions)
3. Inside, add a String tag named "type" and set it to `appliedenergistics2:spatial_storage`
4. Add another Compound tag inside named `generator`, and inside _that_ add another String tag named "type" and set it to `appliedenergistics2:spatial_storage`.

The result should appear as follows:
```
[-] [#] dimensions: 5 entries
 |  [-] [#] appliedenergistics2:spatial_storage: 2 entries
 |   |  [-] [#] generator: 1 entry
 |   |   |   \- [A] type: appliedenergistics2:spatial_storage
 |   |   \- [A] type: appliedenergistics2:spatial_storage
 |  [+] [#] minecraft:overworld: 2 entries
...
